name: ch02
version: '0.1.0'
github: "jship/okasaki-party"
copyright: 2020 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"

extra-source-files:
- package.yaml

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  dependencies:
  - base
  - pretty-simple
  source-dirs: library

tests:
  ch02-test-suite:
    source-dirs: test-suite
    main: Driver.hs
    build-tools:
    - hspec-discover
    dependencies:
    - base
    - hspec
    - ch02
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N -T"'
